"use client";
import React, { useEffect } from "react";
import { useState } from "react";
import { Montserrat } from "next/font/google";
import "./globals.css";
import useThemeSwitcher from "./components/hooks/useThemeSwitcher";
import NavBar from "./components/NavBar";
import Script from "next/script";
import { useRouter } from "next/navigation";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-mont",
});

const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children, className = "" }) {

  const [loading, setLoading] = useState(true);

    useEffect(() => {
    const timer = setTimeout(() => {
      setLoading(false);
    }, 2000);
    return () => clearTimeout(timer);
    }, []);

  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} bg-desert  text-darkPurple w-full min-h-screen dark:bg-dark ${className}`}
      >
        <Script id="theme-switcher" strategy="beforeInteractive">
          if (localStorage.theme === 'dark' || (!('theme' in localStorage) &&
          window.matchMedia('(prefers-color-scheme: dark)').matches)){" "}
          {`document.documentElement.classList.add("dark")`} else{" "}
          {`document.documentElement.classList.remove("dark")`}
        </Script>
        <NavBar />
        {loading && (
          <div className="flex justify-center items-center h-screen">
            <div className="animate-spin rounded-full h-32 w-32 border-t-2 border-b-2 border-snow"></div>
          </div>
        )}
        {!loading && children}
      </body>
    </html>
  );
}
