"use client";
import React from "react";
import { Montserrat } from "next/font/google";
import "./globals.css";
import useThemeSwitcher from "./components/hooks/useThemeSwitcher";
import NavBar from "./components/NavBar";
import Script from "next/script";


const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-mont",
});

const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children, className = "" }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} bg-desert  text-darkPurple w-full min-h-screen dark:bg-dark ${className}`}
      >
        <Script id="theme-switcher" strategy="beforeInteractive">
          
          
          if (localStorage.theme === 'dark' || (!('theme' in localStorage) &&
          window.matchMedia('(prefers-color-scheme: dark)').matches)){" "}
          {`document.documentElement.classList.add("dark")`} else{" "}
          {`document.documentElement.classList.remove("dark")`}
          
        </Script>
        <NavBar />

        {children}
        
      </body>
    </html>
  );
}
