'use client';
import React from "react";
import {useState} from "react";
import { Montserrat } from "next/font/google";
import "./globals.css";



const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-mont",
});

const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
  
  
};

export default function RootLayout({ children }) {

 

  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} bg-desert text-darkPurple w-full min-h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
